### ISSUE TITLE
can't set an authentication for MQTT

### ISSUE THREAD

**Issue by alco28** [marvinroger/homie-esp8266-setup#1] opened 2016-10-15 11:14 UTC
When I use this web app, I can't set an MQTT authentication, I fill the form, the "next" button lights up, but doesn't go to the next page. I only works without the flagged 'Use MQTT authentication' button.

**Comment by marvinroger** [comment] 2016-10-15 11:24
This was fixed in https://github.com/marvinroger/homie-esp8266-setup/commit/0c1b2043303d8da67c3e7d0726cfe9602e6ee0e4 and the webpage was updated at 9:05AM GMT (two hours ago). Did you use the web app after this, or before?

**Comment by alco28** [comment] 2016-10-15 11:35
I used it after 9:05AM, it turns out that you solved **that** problem, but created a new one. sorry Marvin. 
There is an JSON error after the last page:

![screenshot_2016-10-15-13-27-17 1](https://cloud.githubusercontent.com/assets/1846650/19409759/c5638bea-92db-11e6-8e5f-b24cf2b90c16.png)

also on the android app, my MQTT username is a short one (esp8266) the password contains string and number values and it's 13 long (like this example: 44Gp8PKnHy633).

**Comment by marvinroger** [comment] 2016-10-15 12:25
Can you test on a computer, and send me the JSON config sent to `PUT /config`, with the developer tools (F12)? Of course, strip the sensitive information, I only need the structure of the data.

**Comment by marvinroger** [comment] 2016-10-15 23:52
@alco28 don't bother provide what I asked in the last comment, I identified the issue. It comes from homie-esp8266, not the setup. This issue is therefore now tracked there https://github.com/marvinroger/homie-esp8266/issues/178, so subscribe to this issue if you'd like to be notified when the problem is fixed.

**Closed as completed by marvinroger** 2016-10-15 23:52 UTC
Labels: bug

**Comment by marvinroger** [comment] 2016-10-16 17:20
@alco28 please pull the latest `homie-esp8266`, it it fixed there. 😉
